from src.model import Storage
from gui.main_window import Ui_main_window
from PyQt5.QtWidgets import (QMainWindow, QTableWidgetItem, QHeaderView,
                            QFileDialog)


class Interface(QMainWindow, Ui_main_window):
    """
        Handles all the events related to the interface, connecting
        the events generated by the user with their proper handlers. Part of 
        the view compontent of a MVC architecture.
    """
    def __init__(self):
        QMainWindow.__init__(self)
        self.setupUi(self)

        self.new_book_button.clicked.connect(self._insert_book)
        self.sort_books_button.clicked.connect(self._sort_books)
        self.clear_button.clicked.connect(self._clear_table)
        
        self.load_books.triggered.connect(self._load_books)

        self._storage = Storage()

    def _insert_book(self):
        pass

    def _sort_books(self):
        self._update_sorted_table(self._storage.sort())

    def _load_books(self):
        file, _ = QFileDialog.getOpenFileName(self)
        if(file):
            self._storage.load_json(file)
        self._update_books_table()

    def _update_books_table(self):
        for book in self._storage.books:
            actual_row_index = self.books_table.rowCount()
            self.books_table.insertRow(actual_row_index)

            for i in range(len(book)):
                attribute = self.books_table.horizontalHeaderItem(i).text()
                attribute = attribute.lower()
                self.books_table.setItem(actual_row_index, i,
                                         QTableWidgetItem(str(book[attribute]))
                                         )

    def _update_sorted_table(self, sorted):
        self.sorted_table.setRowCount(0)

        for book in sorted:
            actual_row_index = self.sorted_table.rowCount()
            self.sorted_table.insertRow(actual_row_index)

            for i in range(len(book)):
                attribute = self.sorted_table.horizontalHeaderItem(i).text()
                attribute = attribute.lower()
                self.sorted_table.setItem(actual_row_index, i,
                                          QTableWidgetItem(str(book[attribute]))
                                          )

    def _clear_table(self):
        self._storage.set_books([])
        self.books_table.setRowCount(0)
