from gui.main_window import Ui_main_window
from PyQt5.QtWidgets import QMainWindow, QTableWidgetItem


class Interface(QMainWindow, Ui_main_window):
    """
        Handles all the events related to the interface, connecting
        the events generated by the user with their proper handlers. Part of 
        the view compontent of a MVC architecture.
    """
    def __init__(self):
        QMainWindow.__init__(self)
        self.setupUi(self)

        self.new_book_button.clicked.connect(self._insert_book)
        self.sort_books_button.clicked.connect(self._sort_books)
        
        self.load_books.triggered.connect(self._load_books)

    def _insert_book(self):
        pass


    def _sort_books(self):
        pass

    def _load_books(self):
        pass
